version: '2'
services:
  web:
    container_name: b-grocery-list-dev
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - "4201:4200"
    volumes:
      - ./src:/opt/app/src
